name: Build and Push Docker Image to Aliyun

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  IMAGE_NAME: jmcomic-webui
  ALIYUN_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  ALIYUN_NAMESPACE: starfishes
  ALIYUN_IMAGE: registry.cn-hangzhou.aliyuncs.com/starfishes/jmcomic-webui

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download Linux static binary (app_linux_amd64)
        run: |
            wget -O Docker/native/project/app \
            https://github.com/Jackxwb/My-JMComic-WebUI/releases/latest/download/app_linux_amd64
            chmod +x Docker/native/project/app
            ls -lh Docker/native/project/app


      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build Docker image
        run: |
          cd Docker/native
          docker build -t $ALIYUN_IMAGE:latest .

      - name: Push Docker image (latest)
        run: |
          docker push $ALIYUN_IMAGE:latest

      - name: Push version tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker tag $ALIYUN_IMAGE:latest $ALIYUN_IMAGE:$VERSION
          docker push $ALIYUN_IMAGE:$VERSION
